import { Outfit } from "next/font/google";
import "./globals.css";
import { HeroUIProvider } from "@heroui/react";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased`}
        data-new-gr-c-s-check-loaded="14.1241.0"
        data-gr-ext-installed=""
        >
        <HeroUIProvider>
        {children}
      </HeroUIProvider>
      </body>
    </html>
  );
}
